name: ci
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # https://github.com/goreleaser/goreleaser-action/issues/56

      - name: test
        run: make docker-acc
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APPLICATION_KEY: ${{ secrets.DATADOG_APPLICATION_KEY }}
          STATUSPAGE_PAGE: ${{ secrets.STATUSPAGE_PAGE }}
          STATUSPAGE_PAGE_2: ${{ secrets.STATUSPAGE_PAGE_2 }}
          STATUSPAGE_TOKEN: ${{ secrets.STATUSPAGE_TOKEN }}

  goreleaser:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Import GPG key
        id: import_gpg
        uses: yannh/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Run GoReleaser
        uses: yannh/goreleaser-action@v2.8.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
